Feature: create accounts


  @SmokeTest
  Scenario: Check all in category
    Given User able to click everything

    @RegressionTest
  Scenario: verify the logo
    Given user very the logo

      @End2EndTest
  Scenario: User able to write search somrthing
    Given User able to write on the search box

  @SmokeTest @RegressionTest
  Scenario: target create account
    Given User is click on sign in

  @RegressionTest
  Scenario: guests recived weekly offers
    Given check inside the weekly

  Scenario: user close the browser
    Given get out